version: '2'
services:
    proxy:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
            - ./logs:/usr/local/ezproxy/logs
        env_file:
            - ./env/proxy.env
        network_mode: bridge
        ports:
            - "192.168.128.213:80:80"
            - "192.168.128.213:443:443"
        restart: always
